/**
 * Country Reference Data
 * Used by country_management.php for country suggestions and autofill
 */
const COUNTRY_REF = [
  {name:'Afghanistan',iso2:'AF',iso3:'AFG',phone:'+93',currency:'AFN',tz:'Asia/Kabul',locale:'fa_AF'},
  {name:'Albania',iso2:'AL',iso3:'ALB',phone:'+355',currency:'ALL',tz:'Europe/Tirane',locale:'sq_AL'},
  {name:'Algeria',iso2:'DZ',iso3:'DZA',phone:'+213',currency:'DZD',tz:'Africa/Algiers',locale:'ar_DZ'},
  {name:'Andorra',iso2:'AD',iso3:'AND',phone:'+376',currency:'EUR',tz:'Europe/Andorra',locale:'ca_AD'},
  {name:'Angola',iso2:'AO',iso3:'AGO',phone:'+244',currency:'AOA',tz:'Africa/Luanda',locale:'pt_AO'},
  {name:'Antigua and Barbuda',iso2:'AG',iso3:'ATG',phone:'+1-268',currency:'XCD',tz:'America/Antigua',locale:'en_AG'},
  {name:'Argentina',iso2:'AR',iso3:'ARG',phone:'+54',currency:'ARS',tz:'America/Argentina/Buenos_Aires',locale:'es_AR'},
  {name:'Armenia',iso2:'AM',iso3:'ARM',phone:'+374',currency:'AMD',tz:'Asia/Yerevan',locale:'hy_AM'},
  {name:'Australia',iso2:'AU',iso3:'AUS',phone:'+61',currency:'AUD',tz:'Australia/Sydney',locale:'en_AU'},
  {name:'Austria',iso2:'AT',iso3:'AUT',phone:'+43',currency:'EUR',tz:'Europe/Vienna',locale:'de_AT'},
  {name:'Azerbaijan',iso2:'AZ',iso3:'AZE',phone:'+994',currency:'AZN',tz:'Asia/Baku',locale:'az_AZ'},

  {name:'Bahamas',iso2:'BS',iso3:'BHS',phone:'+1-242',currency:'BSD',tz:'America/Nassau',locale:'en_BS'},
  {name:'Bahrain',iso2:'BH',iso3:'BHR',phone:'+973',currency:'BHD',tz:'Asia/Bahrain',locale:'ar_BH'},
  {name:'Bangladesh',iso2:'BD',iso3:'BGD',phone:'+880',currency:'BDT',tz:'Asia/Dhaka',locale:'bn_BD'},
  {name:'Barbados',iso2:'BB',iso3:'BRB',phone:'+1-246',currency:'BBD',tz:'America/Barbados',locale:'en_BB'},
  {name:'Belarus',iso2:'BY',iso3:'BLR',phone:'+375',currency:'BYN',tz:'Europe/Minsk',locale:'be_BY'},
  {name:'Belgium',iso2:'BE',iso3:'BEL',phone:'+32',currency:'EUR',tz:'Europe/Brussels',locale:'nl_BE'},
  {name:'Belize',iso2:'BZ',iso3:'BLZ',phone:'+501',currency:'BZD',tz:'America/Belize',locale:'en_BZ'},
  {name:'Benin',iso2:'BJ',iso3:'BEN',phone:'+229',currency:'XOF',tz:'Africa/Porto-Novo',locale:'fr_BJ'},
  {name:'Bhutan',iso2:'BT',iso3:'BTN',phone:'+975',currency:'BTN',tz:'Asia/Thimphu',locale:'dz_BT'},
  {name:'Bolivia',iso2:'BO',iso3:'BOL',phone:'+591',currency:'BOB',tz:'America/La_Paz',locale:'es_BO'},
  {name:'Bosnia and Herzegovina',iso2:'BA',iso3:'BIH',phone:'+387',currency:'BAM',tz:'Europe/Sarajevo',locale:'bs_BA'},
  {name:'Botswana',iso2:'BW',iso3:'BWA',phone:'+267',currency:'BWP',tz:'Africa/Gaborone',locale:'en_BW'},
  {name:'Brazil',iso2:'BR',iso3:'BRA',phone:'+55',currency:'BRL',tz:'America/Sao_Paulo',locale:'pt_BR'},
  {name:'Brunei',iso2:'BN',iso3:'BRN',phone:'+673',currency:'BND',tz:'Asia/Brunei',locale:'ms_BN'},
  {name:'Bulgaria',iso2:'BG',iso3:'BGR',phone:'+359',currency:'BGN',tz:'Europe/Sofia',locale:'bg_BG'},
  {name:'Burkina Faso',iso2:'BF',iso3:'BFA',phone:'+226',currency:'XOF',tz:'Africa/Ouagadougou',locale:'fr_BF'},
  {name:'Burundi',iso2:'BI',iso3:'BDI',phone:'+257',currency:'BIF',tz:'Africa/Bujumbura',locale:'fr_BI'},

  {name:'Cabo Verde',iso2:'CV',iso3:'CPV',phone:'+238',currency:'CVE',tz:'Atlantic/Cape_Verde',locale:'pt_CV'},
  {name:'Cambodia',iso2:'KH',iso3:'KHM',phone:'+855',currency:'KHR',tz:'Asia/Phnom_Penh',locale:'km_KH'},
  {name:'Cameroon',iso2:'CM',iso3:'CMR',phone:'+237',currency:'XAF',tz:'Africa/Douala',locale:'fr_CM'},
  {name:'Canada',iso2:'CA',iso3:'CAN',phone:'+1',currency:'CAD',tz:'America/Toronto',locale:'en_CA'},
  {name:'Central African Republic',iso2:'CF',iso3:'CAF',phone:'+236',currency:'XAF',tz:'Africa/Bangui',locale:'fr_CF'},
  {name:'Chad',iso2:'TD',iso3:'TCD',phone:'+235',currency:'XAF',tz:'Africa/Ndjamena',locale:'fr_TD'},
  {name:'Chile',iso2:'CL',iso3:'CHL',phone:'+56',currency:'CLP',tz:'America/Santiago',locale:'es_CL'},
  {name:'China',iso2:'CN',iso3:'CHN',phone:'+86',currency:'CNY',tz:'Asia/Shanghai',locale:'zh_CN'},
  {name:'Colombia',iso2:'CO',iso3:'COL',phone:'+57',currency:'COP',tz:'America/Bogota',locale:'es_CO'},
  {name:'Comoros',iso2:'KM',iso3:'COM',phone:'+269',currency:'KMF',tz:'Indian/Comoro',locale:'ar_KM'},
  {name:'Congo (Republic of the)',iso2:'CG',iso3:'COG',phone:'+242',currency:'XAF',tz:'Africa/Brazzaville',locale:'fr_CG'},
  {name:'Congo (Democratic Republic)',iso2:'CD',iso3:'COD',phone:'+243',currency:'CDF',tz:'Africa/Kinshasa',locale:'fr_CD'},
  {name:'Costa Rica',iso2:'CR',iso3:'CRI',phone:'+506',currency:'CRC',tz:'America/Costa_Rica',locale:'es_CR'},
  {name:'Côte d\'Ivoire',iso2:'CI',iso3:'CIV',phone:'+225',currency:'XOF',tz:'Africa/Abidjan',locale:'fr_CI'},
  {name:'Croatia',iso2:'HR',iso3:'HRV',phone:'+385',currency:'EUR',tz:'Europe/Zagreb',locale:'hr_HR'},
  {name:'Cuba',iso2:'CU',iso3:'CUB',phone:'+53',currency:'CUP',tz:'America/Havana',locale:'es_CU'},
  {name:'Cyprus',iso2:'CY',iso3:'CYP',phone:'+357',currency:'EUR',tz:'Asia/Nicosia',locale:'el_CY'},
  {name:'Czechia',iso2:'CZ',iso3:'CZE',phone:'+420',currency:'CZK',tz:'Europe/Prague',locale:'cs_CZ'},

  {name:'Denmark',iso2:'DK',iso3:'DNK',phone:'+45',currency:'DKK',tz:'Europe/Copenhagen',locale:'da_DK'},
  {name:'Djibouti',iso2:'DJ',iso3:'DJI',phone:'+253',currency:'DJF',tz:'Africa/Djibouti',locale:'fr_DJ'},
  {name:'Dominica',iso2:'DM',iso3:'DMA',phone:'+1-767',currency:'XCD',tz:'America/Dominica',locale:'en_DM'},
  {name:'Dominican Republic',iso2:'DO',iso3:'DOM',phone:'+1-809',currency:'DOP',tz:'America/Santo_Domingo',locale:'es_DO'},

  {name:'Ecuador',iso2:'EC',iso3:'ECU',phone:'+593',currency:'USD',tz:'America/Guayaquil',locale:'es_EC'},
  {name:'Egypt',iso2:'EG',iso3:'EGY',phone:'+20',currency:'EGP',tz:'Africa/Cairo',locale:'ar_EG'},
  {name:'El Salvador',iso2:'SV',iso3:'SLV',phone:'+503',currency:'USD',tz:'America/El_Salvador',locale:'es_SV'},
  {name:'Equatorial Guinea',iso2:'GQ',iso3:'GNQ',phone:'+240',currency:'XAF',tz:'Africa/Malabo',locale:'es_GQ'},
  {name:'Eritrea',iso2:'ER',iso3:'ERI',phone:'+291',currency:'ERN',tz:'Africa/Asmara',locale:'ti_ER'},
  {name:'Estonia',iso2:'EE',iso3:'EST',phone:'+372',currency:'EUR',tz:'Europe/Tallinn',locale:'et_EE'},
  {name:'Eswatini',iso2:'SZ',iso3:'SWZ',phone:'+268',currency:'SZL',tz:'Africa/Mbabane',locale:'en_SZ'},
  {name:'Ethiopia',iso2:'ET',iso3:'ETH',phone:'+251',currency:'ETB',tz:'Africa/Addis_Ababa',locale:'am_ET'},

  {name:'Fiji',iso2:'FJ',iso3:'FJI',phone:'+679',currency:'FJD',tz:'Pacific/Fiji',locale:'en_FJ'},
  {name:'Finland',iso2:'FI',iso3:'FIN',phone:'+358',currency:'EUR',tz:'Europe/Helsinki',locale:'fi_FI'},
  {name:'France',iso2:'FR',iso3:'FRA',phone:'+33',currency:'EUR',tz:'Europe/Paris',locale:'fr_FR'},

  {name:'Gabon',iso2:'GA',iso3:'GAB',phone:'+241',currency:'XAF',tz:'Africa/Libreville',locale:'fr_GA'},
  {name:'Gambia',iso2:'GM',iso3:'GMB',phone:'+220',currency:'GMD',tz:'Africa/Banjul',locale:'en_GM'},
  {name:'Georgia',iso2:'GE',iso3:'GEO',phone:'+995',currency:'GEL',tz:'Asia/Tbilisi',locale:'ka_GE'},
  {name:'Germany',iso2:'DE',iso3:'DEU',phone:'+49',currency:'EUR',tz:'Europe/Berlin',locale:'de_DE'},
  {name:'Ghana',iso2:'GH',iso3:'GHA',phone:'+233',currency:'GHS',tz:'Africa/Accra',locale:'en_GH'},
  {name:'Greece',iso2:'GR',iso3:'GRC',phone:'+30',currency:'EUR',tz:'Europe/Athens',locale:'el_GR'},
  {name:'Grenada',iso2:'GD',iso3:'GRD',phone:'+1-473',currency:'XCD',tz:'America/Grenada',locale:'en_GD'},
  {name:'Guatemala',iso2:'GT',iso3:'GTM',phone:'+502',currency:'GTQ',tz:'America/Guatemala',locale:'es_GT'},
  {name:'Guinea',iso2:'GN',iso3:'GIN',phone:'+224',currency:'GNF',tz:'Africa/Conakry',locale:'fr_GN'},
  {name:'Guinea-Bissau',iso2:'GW',iso3:'GNB',phone:'+245',currency:'XOF',tz:'Africa/Bissau',locale:'pt_GW'},
  {name:'Guyana',iso2:'GY',iso3:'GUY',phone:'+592',currency:'GYD',tz:'America/Guyana',locale:'en_GY'},

  {name:'Haiti',iso2:'HT',iso3:'HTI',phone:'+509',currency:'HTG',tz:'America/Port-au-Prince',locale:'fr_HT'},
  {name:'Honduras',iso2:'HN',iso3:'HND',phone:'+504',currency:'HNL',tz:'America/Tegucigalpa',locale:'es_HN'},
  {name:'Hungary',iso2:'HU',iso3:'HUN',phone:'+36',currency:'HUF',tz:'Europe/Budapest',locale:'hu_HU'},

  {name:'Iceland',iso2:'IS',iso3:'ISL',phone:'+354',currency:'ISK',tz:'Atlantic/Reykjavik',locale:'is_IS'},
  {name:'India',iso2:'IN',iso3:'IND',phone:'+91',currency:'INR',tz:'Asia/Kolkata',locale:'en_IN'},
  {name:'Indonesia',iso2:'ID',iso3:'IDN',phone:'+62',currency:'IDR',tz:'Asia/Jakarta',locale:'id_ID'},
  {name:'Iran',iso2:'IR',iso3:'IRN',phone:'+98',currency:'IRR',tz:'Asia/Tehran',locale:'fa_IR'},
  {name:'Iraq',iso2:'IQ',iso3:'IRQ',phone:'+964',currency:'IQD',tz:'Asia/Baghdad',locale:'ar_IQ'},
  {name:'Ireland',iso2:'IE',iso3:'IRL',phone:'+353',currency:'EUR',tz:'Europe/Dublin',locale:'en_IE'},
  {name:'Israel',iso2:'IL',iso3:'ISR',phone:'+972',currency:'ILS',tz:'Asia/Jerusalem',locale:'he_IL'},
  {name:'Italy',iso2:'IT',iso3:'ITA',phone:'+39',currency:'EUR',tz:'Europe/Rome',locale:'it_IT'},

  {name:'Jamaica',iso2:'JM',iso3:'JAM',phone:'+1-876',currency:'JMD',tz:'America/Jamaica',locale:'en_JM'},
  {name:'Japan',iso2:'JP',iso3:'JPN',phone:'+81',currency:'JPY',tz:'Asia/Tokyo',locale:'ja_JP'},
  {name:'Jordan',iso2:'JO',iso3:'JOR',phone:'+962',currency:'JOD',tz:'Asia/Amman',locale:'ar_JO'},

  {name:'Kazakhstan',iso2:'KZ',iso3:'KAZ',phone:'+7',currency:'KZT',tz:'Asia/Almaty',locale:'kk_KZ'},
  {name:'Kenya',iso2:'KE',iso3:'KEN',phone:'+254',currency:'KES',tz:'Africa/Nairobi',locale:'en_KE'},
  {name:'Kiribati',iso2:'KI',iso3:'KIR',phone:'+686',currency:'AUD',tz:'Pacific/Tarawa',locale:'en_KI'},
  {name:'Kuwait',iso2:'KW',iso3:'KWT',phone:'+965',currency:'KWD',tz:'Asia/Kuwait',locale:'ar_KW'},
  {name:'Kyrgyzstan',iso2:'KG',iso3:'KGZ',phone:'+996',currency:'KGS',tz:'Asia/Bishkek',locale:'ky_KG'},

  {name:'Laos',iso2:'LA',iso3:'LAO',phone:'+856',currency:'LAK',tz:'Asia/Vientiane',locale:'lo_LA'},
  {name:'Latvia',iso2:'LV',iso3:'LVA',phone:'+371',currency:'EUR',tz:'Europe/Riga',locale:'lv_LV'},
  {name:'Lebanon',iso2:'LB',iso3:'LBN',phone:'+961',currency:'LBP',tz:'Asia/Beirut',locale:'ar_LB'},
  {name:'Lesotho',iso2:'LS',iso3:'LSO',phone:'+266',currency:'LSL',tz:'Africa/Maseru',locale:'en_LS'},
  {name:'Liberia',iso2:'LR',iso3:'LBR',phone:'+231',currency:'LRD',tz:'Africa/Monrovia',locale:'en_LR'},
  {name:'Libya',iso2:'LY',iso3:'LBY',phone:'+218',currency:'LYD',tz:'Africa/Tripoli',locale:'ar_LY'},
  {name:'Liechtenstein',iso2:'LI',iso3:'LIE',phone:'+423',currency:'CHF',tz:'Europe/Vaduz',locale:'de_LI'},
  {name:'Lithuania',iso2:'LT',iso3:'LTU',phone:'+370',currency:'EUR',tz:'Europe/Vilnius',locale:'lt_LT'},
  {name:'Luxembourg',iso2:'LU',iso3:'LUX',phone:'+352',currency:'EUR',tz:'Europe/Luxembourg',locale:'fr_LU'},

  {name:'Madagascar',iso2:'MG',iso3:'MDG',phone:'+261',currency:'MGA',tz:'Indian/Antananarivo',locale:'fr_MG'},
  {name:'Malawi',iso2:'MW',iso3:'MWI',phone:'+265',currency:'MWK',tz:'Africa/Blantyre',locale:'en_MW'},
  {name:'Malaysia',iso2:'MY',iso3:'MYS',phone:'+60',currency:'MYR',tz:'Asia/Kuala_Lumpur',locale:'ms_MY'},
  {name:'Maldives',iso2:'MV',iso3:'MDV',phone:'+960',currency:'MVR',tz:'Indian/Maldives',locale:'dv_MV'},
  {name:'Mali',iso2:'ML',iso3:'MLI',phone:'+223',currency:'XOF',tz:'Africa/Bamako',locale:'fr_ML'},
  {name:'Malta',iso2:'MT',iso3:'MLT',phone:'+356',currency:'EUR',tz:'Europe/Malta',locale:'mt_MT'},
  {name:'Marshall Islands',iso2:'MH',iso3:'MHL',phone:'+692',currency:'USD',tz:'Pacific/Majuro',locale:'en_MH'},
  {name:'Mauritania',iso2:'MR',iso3:'MRT',phone:'+222',currency:'MRU',tz:'Africa/Nouakchott',locale:'ar_MR'},
  {name:'Mauritius',iso2:'MU',iso3:'MUS',phone:'+230',currency:'MUR',tz:'Indian/Mauritius',locale:'en_MU'},
  {name:'Mexico',iso2:'MX',iso3:'MEX',phone:'+52',currency:'MXN',tz:'America/Mexico_City',locale:'es_MX'},
  {name:'Micronesia',iso2:'FM',iso3:'FSM',phone:'+691',currency:'USD',tz:'Pacific/Pohnpei',locale:'en_FM'},
  {name:'Moldova',iso2:'MD',iso3:'MDA',phone:'+373',currency:'MDL',tz:'Europe/Chisinau',locale:'ro_MD'},
  {name:'Monaco',iso2:'MC',iso3:'MCO',phone:'+377',currency:'EUR',tz:'Europe/Monaco',locale:'fr_MC'},
  {name:'Mongolia',iso2:'MN',iso3:'MNG',phone:'+976',currency:'MNT',tz:'Asia/Ulaanbaatar',locale:'mn_MN'},
  {name:'Montenegro',iso2:'ME',iso3:'MNE',phone:'+382',currency:'EUR',tz:'Europe/Podgorica',locale:'sr_ME'},
  {name:'Morocco',iso2:'MA',iso3:'MAR',phone:'+212',currency:'MAD',tz:'Africa/Casablanca',locale:'ar_MA'},
  {name:'Mozambique',iso2:'MZ',iso3:'MOZ',phone:'+258',currency:'MZN',tz:'Africa/Maputo',locale:'pt_MZ'},
  {name:'Myanmar',iso2:'MM',iso3:'MMR',phone:'+95',currency:'MMK',tz:'Asia/Yangon',locale:'my_MM'},

  {name:'Namibia',iso2:'NA',iso3:'NAM',phone:'+264',currency:'NAD',tz:'Africa/Windhoek',locale:'en_NA'},
  {name:'Nauru',iso2:'NR',iso3:'NRU',phone:'+674',currency:'AUD',tz:'Pacific/Nauru',locale:'en_NR'},
  {name:'Nepal',iso2:'NP',iso3:'NPL',phone:'+977',currency:'NPR',tz:'Asia/Kathmandu',locale:'ne_NP'},
  {name:'Netherlands',iso2:'NL',iso3:'NLD',phone:'+31',currency:'EUR',tz:'Europe/Amsterdam',locale:'nl_NL'},
  {name:'New Zealand',iso2:'NZ',iso3:'NZL',phone:'+64',currency:'NZD',tz:'Pacific/Auckland',locale:'en_NZ'},
  {name:'Nicaragua',iso2:'NI',iso3:'NIC',phone:'+505',currency:'NIO',tz:'America/Managua',locale:'es_NI'},
  {name:'Niger',iso2:'NE',iso3:'NER',phone:'+227',currency:'XOF',tz:'Africa/Niamey',locale:'fr_NE'},
  {name:'Nigeria',iso2:'NG',iso3:'NGA',phone:'+234',currency:'NGN',tz:'Africa/Lagos',locale:'en_NG'},
  {name:'North Macedonia',iso2:'MK',iso3:'MKD',phone:'+389',currency:'MKD',tz:'Europe/Skopje',locale:'mk_MK'},
  {name:'Norway',iso2:'NO',iso3:'NOR',phone:'+47',currency:'NOK',tz:'Europe/Oslo',locale:'nb_NO'},

  {name:'Oman',iso2:'OM',iso3:'OMN',phone:'+968',currency:'OMR',tz:'Asia/Muscat',locale:'ar_OM'},

  {name:'Pakistan',iso2:'PK',iso3:'PAK',phone:'+92',currency:'PKR',tz:'Asia/Karachi',locale:'ur_PK'},
  {name:'Palau',iso2:'PW',iso3:'PLW',phone:'+680',currency:'USD',tz:'Pacific/Palau',locale:'en_PW'},
  {name:'Panama',iso2:'PA',iso3:'PAN',phone:'+507',currency:'PAB',tz:'America/Panama',locale:'es_PA'},
  {name:'Papua New Guinea',iso2:'PG',iso3:'PNG',phone:'+675',currency:'PGK',tz:'Pacific/Port_Moresby',locale:'en_PG'},
  {name:'Paraguay',iso2:'PY',iso3:'PRY',phone:'+595',currency:'PYG',tz:'America/Asuncion',locale:'es_PY'},
  {name:'Peru',iso2:'PE',iso3:'PER',phone:'+51',currency:'PEN',tz:'America/Lima',locale:'es_PE'},
  {name:'Philippines',iso2:'PH',iso3:'PHL',phone:'+63',currency:'PHP',tz:'Asia/Manila',locale:'en_PH'},
  {name:'Poland',iso2:'PL',iso3:'POL',phone:'+48',currency:'PLN',tz:'Europe/Warsaw',locale:'pl_PL'},
  {name:'Portugal',iso2:'PT',iso3:'PRT',phone:'+351',currency:'EUR',tz:'Europe/Lisbon',locale:'pt_PT'},

  {name:'Qatar',iso2:'QA',iso3:'QAT',phone:'+974',currency:'QAR',tz:'Asia/Qatar',locale:'ar_QA'},

  {name:'Romania',iso2:'RO',iso3:'ROU',phone:'+40',currency:'RON',tz:'Europe/Bucharest',locale:'ro_RO'},
  {name:'Russia',iso2:'RU',iso3:'RUS',phone:'+7',currency:'RUB',tz:'Europe/Moscow',locale:'ru_RU'},
  {name:'Rwanda',iso2:'RW',iso3:'RWA',phone:'+250',currency:'RWF',tz:'Africa/Kigali',locale:'rw_RW'},

  {name:'Saint Kitts and Nevis',iso2:'KN',iso3:'KNA',phone:'+1-869',currency:'XCD',tz:'America/St_Kitts',locale:'en_KN'},
  {name:'Saint Lucia',iso2:'LC',iso3:'LCA',phone:'+1-758',currency:'XCD',tz:'America/St_Lucia',locale:'en_LC'},
  {name:'Saint Vincent and the Grenadines',iso2:'VC',iso3:'VCT',phone:'+1-784',currency:'XCD',tz:'America/St_Vincent',locale:'en_VC'},
  {name:'Samoa',iso2:'WS',iso3:'WSM',phone:'+685',currency:'WST',tz:'Pacific/Apia',locale:'en_WS'},
  {name:'San Marino',iso2:'SM',iso3:'SMR',phone:'+378',currency:'EUR',tz:'Europe/San_Marino',locale:'it_SM'},
  {name:'Sao Tome and Principe',iso2:'ST',iso3:'STP',phone:'+239',currency:'STN',tz:'Africa/Sao_Tome',locale:'pt_ST'},
  {name:'Saudi Arabia',iso2:'SA',iso3:'SAU',phone:'+966',currency:'SAR',tz:'Asia/Riyadh',locale:'ar_SA'},
  {name:'Senegal',iso2:'SN',iso3:'SEN',phone:'+221',currency:'XOF',tz:'Africa/Dakar',locale:'fr_SN'},
  {name:'Serbia',iso2:'RS',iso3:'SRB',phone:'+381',currency:'RSD',tz:'Europe/Belgrade',locale:'sr_RS'},
  {name:'Seychelles',iso2:'SC',iso3:'SYC',phone:'+248',currency:'SCR',tz:'Indian/Mahe',locale:'en_SC'},
  {name:'Sierra Leone',iso2:'SL',iso3:'SLE',phone:'+232',currency:'SLE',tz:'Africa/Freetown',locale:'en_SL'},
  {name:'Singapore',iso2:'SG',iso3:'SGP',phone:'+65',currency:'SGD',tz:'Asia/Singapore',locale:'en_SG'},
  {name:'Slovakia',iso2:'SK',iso3:'SVK',phone:'+421',currency:'EUR',tz:'Europe/Bratislava',locale:'sk_SK'},
  {name:'Slovenia',iso2:'SI',iso3:'SVN',phone:'+386',currency:'EUR',tz:'Europe/Ljubljana',locale:'sl_SI'},
  {name:'Solomon Islands',iso2:'SB',iso3:'SLB',phone:'+677',currency:'SBD',tz:'Pacific/Guadalcanal',locale:'en_SB'},
  {name:'Somalia',iso2:'SO',iso3:'SOM',phone:'+252',currency:'SOS',tz:'Africa/Mogadishu',locale:'so_SO'},
  {name:'South Africa',iso2:'ZA',iso3:'ZAF',phone:'+27',currency:'ZAR',tz:'Africa/Johannesburg',locale:'en_ZA'},
  {name:'South Korea',iso2:'KR',iso3:'KOR',phone:'+82',currency:'KRW',tz:'Asia/Seoul',locale:'ko_KR'},
  {name:'South Sudan',iso2:'SS',iso3:'SSD',phone:'+211',currency:'SSP',tz:'Africa/Juba',locale:'en_SS'},
  {name:'Spain',iso2:'ES',iso3:'ESP',phone:'+34',currency:'EUR',tz:'Europe/Madrid',locale:'es_ES'},
  {name:'Sri Lanka',iso2:'LK',iso3:'LKA',phone:'+94',currency:'LKR',tz:'Asia/Colombo',locale:'si_LK'},
  {name:'Sudan',iso2:'SD',iso3:'SDN',phone:'+249',currency:'SDG',tz:'Africa/Khartoum',locale:'ar_SD'},
  {name:'Suriname',iso2:'SR',iso3:'SUR',phone:'+597',currency:'SRD',tz:'America/Paramaribo',locale:'nl_SR'},
  {name:'Sweden',iso2:'SE',iso3:'SWE',phone:'+46',currency:'SEK',tz:'Europe/Stockholm',locale:'sv_SE'},
  {name:'Switzerland',iso2:'CH',iso3:'CHE',phone:'+41',currency:'CHF',tz:'Europe/Zurich',locale:'de_CH'},
  {name:'Syria',iso2:'SY',iso3:'SYR',phone:'+963',currency:'SYP',tz:'Asia/Damascus',locale:'ar_SY'},

  {name:'Taiwan',iso2:'TW',iso3:'TWN',phone:'+886',currency:'TWD',tz:'Asia/Taipei',locale:'zh_TW'},
  {name:'Tajikistan',iso2:'TJ',iso3:'TJK',phone:'+992',currency:'TJS',tz:'Asia/Dushanbe',locale:'tg_TJ'},
  {name:'Tanzania',iso2:'TZ',iso3:'TZA',phone:'+255',currency:'TZS',tz:'Africa/Dar_es_Salaam',locale:'sw_TZ'},
  {name:'Thailand',iso2:'TH',iso3:'THA',phone:'+66',currency:'THB',tz:'Asia/Bangkok',locale:'th_TH'},
  {name:'Timor-Leste',iso2:'TL',iso3:'TLS',phone:'+670',currency:'USD',tz:'Asia/Dili',locale:'pt_TL'},
  {name:'Togo',iso2:'TG',iso3:'TGO',phone:'+228',currency:'XOF',tz:'Africa/Lome',locale:'fr_TG'},
  {name:'Tonga',iso2:'TO',iso3:'TON',phone:'+676',currency:'TOP',tz:'Pacific/Tongatapu',locale:'en_TO'},
  {name:'Trinidad and Tobago',iso2:'TT',iso3:'TTO',phone:'+1-868',currency:'TTD',tz:'America/Port_of_Spain',locale:'en_TT'},
  {name:'Tunisia',iso2:'TN',iso3:'TUN',phone:'+216',currency:'TND',tz:'Africa/Tunis',locale:'ar_TN'},
  {name:'Turkey',iso2:'TR',iso3:'TUR',phone:'+90',currency:'TRY',tz:'Europe/Istanbul',locale:'tr_TR'},
  {name:'Turkmenistan',iso2:'TM',iso3:'TKM',phone:'+993',currency:'TMT',tz:'Asia/Ashgabat',locale:'tk_TM'},
  {name:'Tuvalu',iso2:'TV',iso3:'TUV',phone:'+688',currency:'AUD',tz:'Pacific/Funafuti',locale:'en_TV'},

  {name:'Uganda',iso2:'UG',iso3:'UGA',phone:'+256',currency:'UGX',tz:'Africa/Kampala',locale:'en_UG'},
  {name:'Ukraine',iso2:'UA',iso3:'UKR',phone:'+380',currency:'UAH',tz:'Europe/Kyiv',locale:'uk_UA'},
  {name:'United Arab Emirates',iso2:'AE',iso3:'ARE',phone:'+971',currency:'AED',tz:'Asia/Dubai',locale:'ar_AE'},
  {name:'United Kingdom',iso2:'GB',iso3:'GBR',phone:'+44',currency:'GBP',tz:'Europe/London',locale:'en_GB'},
  {name:'United States',iso2:'US',iso3:'USA',phone:'+1',currency:'USD',tz:'America/New_York',locale:'en_US'},
  {name:'Uruguay',iso2:'UY',iso3:'URY',phone:'+598',currency:'UYU',tz:'America/Montevideo',locale:'es_UY'},
  {name:'Uzbekistan',iso2:'UZ',iso3:'UZB',phone:'+998',currency:'UZS',tz:'Asia/Tashkent',locale:'uz_UZ'},

  {name:'Vanuatu',iso2:'VU',iso3:'VUT',phone:'+678',currency:'VUV',tz:'Pacific/Efate',locale:'en_VU'},
  {name:'Vatican City',iso2:'VA',iso3:'VAT',phone:'+379',currency:'EUR',tz:'Europe/Vatican',locale:'it_VA'},
  {name:'Venezuela',iso2:'VE',iso3:'VEN',phone:'+58',currency:'VES',tz:'America/Caracas',locale:'es_VE'},
  {name:'Vietnam',iso2:'VN',iso3:'VNM',phone:'+84',currency:'VND',tz:'Asia/Ho_Chi_Minh',locale:'vi_VN'},

  {name:'Yemen',iso2:'YE',iso3:'YEM',phone:'+967',currency:'YER',tz:'Asia/Aden',locale:'ar_YE'},

  {name:'Zambia',iso2:'ZM',iso3:'ZMB',phone:'+260',currency:'ZMW',tz:'Africa/Lusaka',locale:'en_ZM'},
  {name:'Zimbabwe',iso2:'ZW',iso3:'ZWE',phone:'+263',currency:'ZWL',tz:'Africa/Harare',locale:'en_ZW'}
];