<?php
/**
 * Analytics Report Template for Invoicr
 * SAFE VERSION – JSON & PDF compatible
 */


    <!-- ================= CLIENTS TABLE ================= -->
    <section class="table-section">
        <h2>Top Clients Summary</h2>

        <table class="summary-table">
            <thead>
                <tr>
                    <th>Client</th>
                    <th>Total Invoices</th>
                    <th>Total Amount</th>
                    <th>Paid</th>
                    <th>Unpaid</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach (($clients ?? []) as $client): ?>
                <tr>
                    <td><?= h($client['client_name'] ?? '') ?></td>
                    <td><?= (int)($client['total_invoices'] ?? 0) ?></td>
                    <td><?= formatCurrency($client['total_amount'] ?? 0) ?></td>
                    <td class="success"><?= (int)($client['paid_count'] ?? 0) ?></td>
                    <td class="danger"><?= (int)($client['unpaid_count'] ?? 0) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </section>

    <!-- ================= FOOTER ================= -->
    <footer class="report-footer">
        <p>Report generated by CSNK / SMC Agency Dashboard</p>
        <p>Page <span class="page-num"></span></p>
    </footer>

</div>

</body>
</html>