<?php
                    <th>Client</th>
                    <th>Total Invoices</th>
            <?php endforeach; ?>
            </tbody>
        </table>
    </section>

    <!-- ================= FOOTER ================= -->
    <footer class="report-footer">
        <p>Report generated by CSNK / SMC Agency Dashboard</p>
        <p>Page <span class="page-num"></span></p>
    </footer>

</div>

</body>
</html>