<?php
/**
 * Analytics Report Template for Invoicr
 * SAFE VERSION – JSON & PDF compatible
 */

/* ===============================
   HELPER FUNCTIONS (MUST BE FIRST)
<body>

<div class="report">

    <!-- ================= HEADER ================= -->
    <header class="report-header">
        <div class="company-logo">
            <img src="<?= h($company[0] ?? '') ?>" alt="Company Logo">
        </div>

        <div class="report-title">
            <h1>Analytics &amp; Payments Report</h1>
            <p>
                Generated: <?= date('F j, Y g:i A') ?><br>
                Company: <?= h($company[1] ?? '') ?>
            </p>
        </div>

        <div class="company-badge">
            <img src="<?= h($company[2] ?? '') ?>" alt="Company Badge">
        </div>
    </header>

    <!-- ================= SUMMARY KPI ================= -->
    <section class="kpis-section">
        <h2>Executive Summary</h2>

        <div class="kpis-grid">
            <div class="kpi-card">
                <h3>Gross Total</h3>
                <div class="kpi-value">
                    <?= formatCurrency($summary['gross'] ?? 0) ?>
                </div>
            </div>

            <div class="kpi-card">
                <h3>Net Revenue</h3>
                <div class="kpi-value">
                    <?= formatCurrency($summary['net'] ?? 0) ?>
                </div>
            </div>

            <div class="kpi-card">
                <h3>Pending</h3>
                <div class="kpi-value danger">
                    <?= formatCurrency($summary['pending'] ?? 0) ?>
                </div>
            </div>

            <div class="kpi-card">
                <h3>Applicants Billed</h3>
                <div class="kpi-value">
                    <?= (int)($kpis['applicants_billed'] ?? 0) ?>
                </div>
            </div>
        </div>
    </section>

    <!-- ================= CHARTS ================= -->
    <section class="charts-section">
        <h2>Visual Analytics</h2>

        <div class="charts-grid">

            <figure class="chart-item">
                <img src="<?= h($chart_status ?? '') ?>" class="chart-img" alt="Payment Status">
                <figcaption>Payment Status Distribution</figcaption>
            </figure>

            <figure class="chart-item">
                <img src="<?= h($chart_methods ?? '') ?>" class="chart-img" alt="Payment Methods">
                <figcaption>Revenue by Payment Method</figcaption>
            </figure>

            <figure class="chart-item full">
                <img src="<?= h($chart_trend ?? '') ?>" class="chart-img" alt="Revenue Trend">
                <figcaption>Revenue Trend Over Time</figcaption>
            </figure>

            <figure class="chart-item">
                <img src="<?= h($chart_timeline ?? '') ?>" class="chart-img" alt="Invoice Timeline">
                <figcaption>Invoice Timeline (Paid vs Pending)</figcaption>
            </figure>

            <figure class="chart-item">
                <img src="<?= h($chart_clients ?? '') ?>" class="chart-img" alt="Top Clients">
                <figcaption>Top Clients by Revenue</figcaption>
            </figure>

        </div>
    </section>

    <!-- ================= CLIENTS TABLE ================= -->
    <section class="table-section">
        <h2>Top Clients Summary</h2>

        <table class="summary-table">
            <thead>
                <tr>
                    <th>Client</th>
                    <th>Total Invoices</th>
                    <th>Total Amount</th>
                    <th>Paid</th>
                    <th>Unpaid</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach (($clients ?? []) as $client): ?>
                <tr>
                    <td><?= h($client['client_name'] ?? '') ?></td>
                    <td><?= (int)($client['total_invoices'] ?? 0) ?></td>
                    <td><?= formatCurrency($client['total_amount'] ?? 0) ?></td>
                    <td class="success"><?= (int)($client['paid_count'] ?? 0) ?></td>
                    <td class="danger"><?= (int)($client['unpaid_count'] ?? 0) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </section>

    <!-- ================= FOOTER ================= -->
    <footer class="report-footer">
        <p>Report generated by CSNK / SMC Agency Dashboard</p>
        <p>Page <span class="page-num"></span></p>
    </footer>

</div>

</body>
</html>